name: Feature Request
description: Suggest an enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Suggest an idea for TextShield
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this solve?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Describe your solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: checkboxes
    id: docs
    attributes:
      label: Checklist
      options:
        - label: I have checked existing issues
        - label: I am willing to contribute
