"""Hunting enums."""

from enum import Enum


class FindingState(str, Enum):
    NEW = "NEW"
    UNDER_REVIEW = "UNDER_REVIEW"
    VALIDATED = "VALIDATED"
    DISMISSED = "DISMISSED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    CONFIRMED = "CONFIRMED"
    EXPIRED = "EXPIRED"
    ARCHIVED = "ARCHIVED"


class FindingType(str, Enum):
    IOC_REUSE = "IOC_REUSE"
    DOMAIN_REUSE = "DOMAIN_REUSE"
    URL_PATTERN_REUSE = "URL_PATTERN_REUSE"
    SENDER_REUSE = "SENDER_REUSE"
    PHONE_REUSE = "PHONE_REUSE"
    EMAIL_REUSE = "EMAIL_REUSE"
    MESSAGE_TEMPLATE_REUSE = "MESSAGE_TEMPLATE_REUSE"
    SEMANTIC_CLUSTER = "SEMANTIC_CLUSTER"
    BEHAVIOR_CLUSTER = "BEHAVIOR_CLUSTER"
    CAMPAIGN_PATTERN = "CAMPAIGN_PATTERN"
    TEMPORAL_ANOMALY = "TEMPORAL_ANOMALY"
    INFRASTRUCTURE_CLUSTER = "INFRASTRUCTURE_CLUSTER"
    EMERGING_PATTERN = "EMERGING_PATTERN"
    SUSPICIOUS_ENTITY = "SUSPICIOUS_ENTITY"
    SUSPICIOUS_RELATIONSHIP = "SUSPICIOUS_RELATIONSHIP"
    CROSS_CHANNEL_PATTERN = "CROSS_CHANNEL_PATTERN"
    UNKNOWN = "UNKNOWN"


class HypothesisState(str, Enum):
    DISCOVERED = "DISCOVERED"
    UNDER_REVIEW = "UNDER_REVIEW"
    LIKELY = "LIKELY"
    CONFIRMED = "CONFIRMED"
    DISMISSED = "DISMISSED"


class RecommendationState(str, Enum):
    PROPOSED = "PROPOSED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DEPLOYED = "DEPLOYED"
    ROLLED_BACK = "ROLLED_BACK"
