"""Research enums."""

from enum import Enum


class ResearchType(str, Enum):
    IOC_ENRICHMENT = "IOC_ENRICHMENT"
    DOMAIN_RESEARCH = "DOMAIN_RESEARCH"
    URL_RESEARCH = "URL_RESEARCH"
    CAMPAIGN_RESEARCH = "CAMPAIGN_RESEARCH"
    INFRASTRUCTURE_RESEARCH = "INFRASTRUCTURE_RESEARCH"
    ACTOR_RESEARCH = "ACTOR_RESEARCH"
    TTP_RESEARCH = "TTP_RESEARCH"
    MESSAGE_PATTERN_RESEARCH = "MESSAGE_PATTERN_RESEARCH"
    EMERGING_THREAT_RESEARCH = "EMERGING_THREAT_RESEARCH"
    ENTITY_RESEARCH = "ENTITY_RESEARCH"
    GENERAL_INVESTIGATION = "GENERAL_INVESTIGATION"


class ResearchState(str, Enum):
    CREATED = "CREATED"
    PLANNED = "PLANNED"
    COLLECTING = "COLLECTING"
    ANALYZING = "ANALYZING"
    VALIDATING = "VALIDATING"
    FUSING = "FUSING"
    READY_FOR_REVIEW = "READY_FOR_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"


class EvidenceType(str, Enum):
    OBSERVED = "OBSERVED"
    REPORTED = "REPORTED"
    INFERRED = "INFERRED"
    CORRELATED = "CORRELATED"
    HYPOTHESIZED = "HYPOTHESIZED"


class KnowledgeState(str, Enum):
    DISCOVERED = "DISCOVERED"
    EXTRACTED = "EXTRACTED"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    PUBLISHED = "PUBLISHED"
    STALE = "STALE"
    REVIEW_REQUIRED = "REVIEW_REQUIRED"
    REVOKED = "REVOKED"
    ARCHIVED = "ARCHIVED"


class ContradictionState(str, Enum):
    UNRESOLVED = "UNRESOLVED"
    RESOLVED = "RESOLVED"
    SOURCE_PRIORITY = "SOURCE_PRIORITY"
    TEMPORAL_DIFFERENCE = "TEMPORAL_DIFFERENCE"
    SCOPE_DIFFERENCE = "SCOPE_DIFFERENCE"
    INSUFFICIENT_DATA = "INSUFFICIENT_DATA"


class SourceType(str, Enum):
    LOCAL_DATABASE = "LOCAL_DATABASE"
    THREAT_INTELLIGENCE_PROVIDER = "THREAT_INTELLIGENCE_PROVIDER"
    RAG_KNOWLEDGE_BASE = "RAG_KNOWLEDGE_BASE"
    THREAT_GRAPH = "THREAT_GRAPH"
    HISTORICAL_ANALYSIS = "HISTORICAL_ANALYSIS"
    ANALYST_FEEDBACK = "ANALYST_FEEDBACK"
    APPROVED_EXTERNAL_SOURCE = "APPROVED_EXTERNAL_SOURCE"
